# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phonenum',
            field=models.IntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名'),
        ),
    ]
