# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180812_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='idcard',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证'),
        ),
    ]
