# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_tem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile_tem',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile_tem',
            name='user',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
