# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180813_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phonenum',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile_tem',
            name='phonenum',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
