# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180813_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_tem',
            name='user_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='user_image', verbose_name='身份证照片'),
        ),
    ]
