# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_tem_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_tem',
            name='email_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='验证码'),
        ),
        migrations.AddField(
            model_name='userprofile_tem',
            name='email_yanzheng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='验证邮箱'),
        ),
    ]
