# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180813_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_yanzheng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='验证邮箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_activation_sure',
            field=models.BooleanField(default=False, verbose_name='是否通过审核'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='user_image', verbose_name='身份证照片'),
        ),
    ]
