# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180813_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_tem',
            name='time_last',
            field=models.TimeField(blank=True, null=True, verbose_name='重新发送时间'),
        ),
    ]
