# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_tem_time_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_tem',
            name='time_last',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='重新发送时间'),
        ),
    ]
