# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='invoice',
            field=models.IntegerField(choices=[(1, '无需发票'), (2, '需要发票')], default=1, verbose_name='是否打印发票'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='invoice_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='发票信息'),
        ),
    ]
