# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180817_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='return_num',
            field=models.IntegerField(default=1, verbose_name='回报数量'),
        ),
    ]
