# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '科技'), (2, '设计'), (3, '公益'), (4, '农业')], default=1, verbose_name='分类')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目名称')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目简介')),
                ('money', models.FloatField(blank=True, default=0.0, null=True, verbose_name='筹资金额')),
                ('time', models.IntegerField(blank=True, default=1, null=True, verbose_name='筹资天数')),
                ('headerimage', models.ImageField(blank=True, null=True, upload_to='header_image', verbose_name='项目头图')),
                ('helpimage', models.ImageField(blank=True, null=True, upload_to='help_image', verbose_name='项目详情')),
                ('usertext', models.CharField(blank=True, max_length=40, null=True, verbose_name='自我介绍')),
                ('usertext_long', models.CharField(blank=True, max_length=400, null=True, verbose_name='详细介绍')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('phone_help', models.CharField(blank=True, max_length=11, null=True, verbose_name='客服电话')),
                ('return_category', models.IntegerField(choices=[(1, '实物回报'), (2, '虚拟物品回报')], default=1, verbose_name='回报类型')),
                ('favnums', models.IntegerField(blank=True, null=True, verbose_name='支持人数')),
                ('schedule', models.FloatField(blank=True, default=0.0, null=True, verbose_name='项目进度')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
    ]
