# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='money_now',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='当前金额'),
        ),
    ]
