# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectprofile_money_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprofile',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='projectprofile',
            name='favnums',
            field=models.IntegerField(default=0, verbose_name='支持人数'),
        ),
    ]
