# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180813_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='state',
            field=models.IntegerField(choices=[(1, '即将开始'), (2, '众筹中'), (3, '众筹成功')], default=2, verbose_name='众筹状态'),
        ),
    ]
