# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectprofile_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectprofile',
            options={'ordering': ['-name'], 'verbose_name': '项目信息', 'verbose_name_plural': '项目信息'},
        ),
        migrations.AlterField(
            model_name='projectprofile',
            name='money_now',
            field=models.FloatField(blank=True, default=0.1, null=True, verbose_name='当前金额'),
        ),
    ]
