# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180814_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='fav_p',
            field=models.IntegerField(default=0, verbose_name='关注人数'),
        ),
    ]
