# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_projectprofile_fav_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='项目发起人'),
        ),
    ]
