# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectprofile_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyReturnFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0.0, verbose_name='支付金额')),
                ('re_text', models.CharField(max_length=200, verbose_name='回报内容')),
                ('re_image', models.ImageField(upload_to='re_image', verbose_name='说明图片')),
                ('re_num', models.IntegerField(default=0, verbose_name='回报数量')),
                ('num_limit', models.IntegerField(default=0, verbose_name='单笔限购')),
                ('freight', models.IntegerField(default=0, verbose_name='运费')),
                ('invoice', models.BooleanField(default=False, verbose_name='是否可开发票')),
                ('re_time', models.IntegerField(default=10, verbose_name='回报时间')),
            ],
            options={
                'verbose_name': '项目回报信息',
                'verbose_name_plural': '项目回报信息',
            },
        ),
        migrations.AlterField(
            model_name='projectprofile',
            name='state',
            field=models.IntegerField(choices=[(1, '即将开始'), (2, '众筹中'), (3, '众筹成功')], default=1, verbose_name='众筹状态'),
        ),
        migrations.AddField(
            model_name='moneyreturnfile',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectProfile', verbose_name='所属项目'),
        ),
    ]
