# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180814_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyreturnfile',
            name='limit',
            field=models.BooleanField(default=False, verbose_name='是否限购'),
        ),
        migrations.AlterField(
            model_name='moneyreturnfile',
            name='num_limit',
            field=models.IntegerField(default=1, verbose_name='单笔限购'),
        ),
    ]
