# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20180814_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprofile',
            name='money_now',
            field=models.FloatField(default=0, verbose_name='当前金额'),
        ),
    ]
