# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20180815_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyreturnfile',
            name='re_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='回报内容'),
        ),
    ]
