# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20180815_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyreturnfile',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='支持人数'),
        ),
    ]
