# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_moneyreturnfile_fav_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='add_level',
            field=models.IntegerField(default=0, verbose_name='广告级别'),
        ),
    ]
