# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0013_projectprofile_add_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=0, verbose_name='关注人数')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectProfile', verbose_name='关注项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注',
            },
        ),
    ]
